version: {build}-{branch}

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby24\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install
  - bundle exec rake db:migrate RAILS_ENV=test

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
